// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKq1Kk2PGeSAJ-kmVQIOHf5MO-sNp96gA',
    appId: '1:599702672930:android:5a99a4f936879d048b5c7b',
    messagingSenderId: '599702672930',
    projectId: 'chat-firebase-flutter-9fbd8',
    storageBucket: 'chat-firebase-flutter-9fbd8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB3-ZvvF4utNlwGjssXlAO41sroQUoCyio',
    appId: '1:599702672930:ios:5f957b47b51511638b5c7b',
    messagingSenderId: '599702672930',
    projectId: 'chat-firebase-flutter-9fbd8',
    storageBucket: 'chat-firebase-flutter-9fbd8.appspot.com',
    iosClientId: '599702672930-7d5eljhv0298panh4hrvgluijm84v06p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatFlutterFirebase',
  );
}
